---

- name: copy k8s.mod.conf
  copy:
    src: k8s.mod.conf
    dest: /etc/modules-load.d/k8s.mod.conf
    owner: root
    group: root
    mode: '0644'

- name: copy k8s.sysctl.conf
  copy:
    src: k8s.sysctl.conf
    dest: /etc/sysctl.d/k8s.sysctl.conf
    owner: root
    group: root
    mode: '0644'

- name: ensure sysctl and module is running
  shell: sysctl --system && modprobe br_netfilter
  register: init_kubernetes
  changed_when: "init_kubernetes.rc != 0"

- name: copy sources.list
  copy:
    src: kubernetes.list
    dest: /etc/apt/sources.list.d/kubernetes.list
    owner: root
    group: root
    mode: '0644'

- name: apt - downloading gpg key
  shell: (wget -qO /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg; wget -qO- https://download.docker.com/linux/debian/gpg | apt-key add -)
  register: apt_key
  changed_when: "apt_key.rc != 0"


- name: apt - update sources list
  apt:
    update_cache: yes

- name: apt - install packages
  apt:
    name: "{{ kubernetes_packages }}"
    state: present

- name: apt - hold kubeadm
  shell: "apt-mark hold kubelet kubeadm kubectl"

- name: containerd - initial configuration
  shell: (containerd config default | tee /etc/containerd/config.toml)

- name: containerd - commenting disabled_plugins, allowing CRI assume
  replace:
    dest: /etc/containerd/config.toml
    regexp: '^(disabled_plugins.*)$'
    replace: '#\1'

- name: restart containerd
  service:
    name: "containerd"
    state: "restarted"
