---
- name: copy k8s.mod.conf
  copy:
    src: k8s.mod.conf
    dest: /etc/modules-load.d/k8s.mod.conf
    owner: root
    group: root
    mode: '0644'

- name: copy k8s.sysctl.conf
  copy:
    src: k8s.sysctl.conf
    dest: /etc/sysctl.d/k8s.sysctl.conf
    owner: root
    group: root
    mode: '0644'

- name: ensure sysctl and module is running
  shell: sysctl --system && modprobe br_netfilter
  register: init_kubernetes
  changed_when: "init_kubernetes.rc != 0"

- name: setup keyrings
  ansible.builtin.shell:
    cmd: mkdir -p /etc/apt/keyrings/

- name: reset keyrings
  ansible.builtin.shell:
    cmd: rm -rf /etc/apt/keyrings/

- name: create keyrings directory
  ansible.builtin.shell:
    cmd: mkdir -p /etc/apt/keyrings/

- name: add apt-key
  ansible.builtin.shell:
    cmd: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: add kubernetes list
  ansible.builtin.shell:
    cmd: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: apt - update sources list
  apt:
    update_cache: yes

- name: apt - install packages
  apt:
    name: "{{ kubernetes_packages }}"
    state: present

- name: apt - hold kubeadm
  shell: "apt-mark hold kubelet kubeadm kubectl"

- name: containerd - initial configuration
  template:
    src: containerd/config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'

- name: restart containerd
  service:
    name: "containerd"
    state: "restarted"

# - include_tasks: nsf-server.yml
#   when: inventory_hostname in groups['cinsfserver']
