---
kubernetes_version: "1.20.1-00"
kubernetes_data_dir: "/kubernetes"
kubernetes_config_path: "/etc/kubernetes"
kubernetes_service: "kubelet"
kubernetes_lock: /tmp/kubernetes.lock
kubernetes_packages:
  - apt-transport-https
  - procps
  - kubeadm={{ kubernetes_version }}
  - kubelet={{ kubernetes_version }}
  - kubectl={{ kubernetes_version }}
  - kubernetes-cni
  - containerd

kubernetes_iface: "eth0"
kubernetes_apiserver_port: 6443
kubernetes_master: 192.168.121.107
