---
kubernetes_version: "1.32.0-1.1"
kubernetes_data_dir: "/kubernetes"
kubernetes_config_path: "/etc/kubernetes"
kubernetes_service: "kubelet"
kubernetes_lock: /tmp/kubernetes.lock
kubernetes_packages:
  - apt-transport-https
  - procps
  - kubeadm={{ kubernetes_version }}
  - kubelet={{ kubernetes_version }}
  - kubectl={{ kubernetes_version }}
  - containerd

kubernetes_iface: "eth1"
kubernetes_apiserver_port: 6443
kubernetes_master: 10.1.0.101

containerd:
  default_config: true
