---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend-developer
rules:
- apiGroups:
  - '*'
  resources:
  - pods
  - pods/exec
  - pods/log
  - deployments
  - deployments/scale
  - services
  - namespaces
  verbs:
  - get
  - list
  - watch
  - update
  - exec
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: frontend-developer
rules:
- apiGroups:
  - ""
  - apps
  resources:
  - pods
  - pods/log
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-deployer
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - deployments
  - replicasets
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
